### ISSUE TITLE
Toggles with text don't work properly

### ISSUE THREAD

**Issue by Javi** [hyochan/react-native-switch-toggle#10]
The button doesn't overlap the left text. 
![image](https://user-images.githubusercontent.com/4081895/51227627-f8d13f00-1933-11e9-8a4d-94d2c43c9d8a.png)

**Comment by hyochan** [comment]
Hi. `react-native-switch-toggle` has been deprecated for a while and is migrated to `react-hook` in [@dooboo-ui/native-switch-toggle](https://www.npmjs.com/package/@dooboo-ui/native-switch-toggle). Hope you guys to check this out.

**Comment by hyochan** [comment]
Version 2 is released just now. @Javi Hope you to try this and come back.

**Comment by CosminPerRam** [comment]
This problem still occurs as of `2.2.1`.
![image](https://user-images.githubusercontent.com/7972857/226333034-9b335e25-aee9-4dff-a7f2-fdb6683a4c1e.png)
![image](https://user-images.githubusercontent.com/7972857/226333060-4627d487-9dc9-4252-8a27-6fceeeba51b8.png)
(circle disappeared offscreen to the right)
