### ISSUE TITLE
Setting containerStyle to an object or StyleSheet that doesn't have padding property results in an error

### ISSUE THREAD

**Issue by pziemkowski** [hyochan/react-native-switch-toggle#16]
This code results in an error:
```
<SwitchToggle
  containerStyle={{ width: 48, height: 16, borderRadius: 8 }}
  switchOn={true}
  onPress={() => {}}
/>
```
Error message:
`Exception thrown while executing UI block: -[NSNull floatValue]: unrecognized selector sent to instance 0x110525f28`

While this code works fine:
```
<SwitchToggle
  containerStyle={{ 
    width: 48, 
    height: 16, 
    borderRadius: 8, 
    padding: 0, // < ------------ Added
  }} 
  switchOn={true}
  onPress={() => {}}
/>
```

(thanks for the lib!)

**Comment by gimoteco** [comment]
The same happened to me, I'm using expo. Every time I set a style attribute that is complete (w/ height and width) results in the above error. It seems that container style is overwriting the original style value resulting in some invalid value.

**Comment by pziemkowski** [comment]
I would say line 70 is the offender:

```
getStart = () => {
        return this.props.type === undefined ? 0 : this.props.type === 0 ? 0 : this.props.containerStyle.padding * 2;
    };
```

It is used to define the starting position of the animated value. `undefined * 2` is `NaN` so it fails to define the native binding.

**Comment by hyochan** [comment]
I've uploaded my code of my own usage. @pziemkowski If you've found any improvements  to `lib` please give any `PR` for others. Thanks.

**Comment by hyochan** [comment]
Hi. `react-native-switch-toggle` has been deprecated for a while and is migrated to `react-hook` in [@dooboo-ui/native-switch-toggle](https://www.npmjs.com/package/@dooboo-ui/native-switch-toggle). Hope you guys to check this out.

**Comment by hyochan** [comment]
Closes due to inactivity. Version 2 is released just now.
