### ISSUE TITLE
Doesn't support RTL

### ISSUE THREAD

**Issue by saadiyakazi** [hyochan/react-native-switch-toggle#33]
<img width="208" alt="Screen Shot 2019-09-05 at 4 38 50 PM" src="https://user-images.githubusercontent.com/50286168/64347044-e9eee800-cffb-11e9-9e19-cadd22c9ee35.png">

For RTL the switch button goes outside view.
Is there any CSS that can be applied to container or circle to fix it ?

**Comment by hyochan** [comment]
I'm sorry but I don't get what is `RTL`. Could you please explain?

**Comment by hyochan** [comment]
Could you make an issue again in [@dooboo-ui/native-switch-toggle](https://www.npmjs.com/package/@dooboo-ui/native-switch-toggle), if you find that this should be still implemented? `react-native-switch-toggle` is currently deprecated.

**Comment by hyochan** [comment]
@shaqash Hey there. It now supports `RTL` from version 2!
