### ISSUE TITLE
Color transition bug when using gray color tones

### ISSUE THREAD

**Issue by Mitchizuky** [hyochan/react-native-switch-toggle#48]
Hello, 

i use this library for a while and dont have any issues so far so all the credits for it. Recently i came across a bug regarding color transition when togling on-off. 

When using gray color tones the color always transitions to a pinkish tone :).

Steps to reproduce:

circleColorOff="gray"
circleColorOn="green"

outcome:

![Screenshot 2021-06-14 at 19 47 11](https://user-images.githubusercontent.com/6384504/121935961-6114ec80-cd49-11eb-9124-319f0c97a573.png)
![Screenshot 2021-06-14 at 19 47 09](https://user-images.githubusercontent.com/6384504/121935964-61ad8300-cd49-11eb-8a4e-6279785320f5.png)

I think the cause for this is the inputRange from background color interpolation. inputRange should be [0,1] instead of [0.5,1].

**Comment by hyochan** [comment]
Thanks for issuing! You may try `2.2.0`!
