### ISSUE TITLE
Package don't support import in typescript project ?

### ISSUE THREAD

**Issue by kytosai** [hyochan/react-native-switch-toggle#49]
**Describe the bug**
Package don't support import in typescript project

**To Reproduce**
1. Install `npm install react-native-switch-toggle --save`
2. Add `import SwitchToggle from "react-native-switch-toggle";`
3. Package don't support declaration file in project

**Expected behavior**
Add declaration file support for package

**Screenshots**
Demo: https://prnt.sc/15ybbgr 

**Desktop (please complete the following information):**

- OS: MacOS
- React native (expo)
- Version 
```
"react-native": "~0.63.4",
"expo": "~41.0.1",
```

**Comment by hyochan** [comment]
Oh.. Thanks you for issuing this. There was a mistake in cloud deployment script. Will fix this soon!

**Comment by hyochan** [comment]
Resolved in `2.2.0`
